package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/mohitmishra786/mdmend/internal/config"
	"github.com/spf13/cobra"
)

type initOptions struct {
	fromMarkdownlint string
	output           string
	force            bool
}

func newInitCmd() *cobra.Command {
	opts := &initOptions{}

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a new mdmend configuration file",
		Long: `Create a new .mdmend.yml configuration file.

Use --from-markdownlint to convert an existing .markdownlint.json file.

Examples:
  mdmend init
  mdmend init --from-markdownlint .markdownlint.json
  mdmend init --from-markdownlint --output .mdmend.yml`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit(opts)
		},
	}

	cmd.Flags().StringVar(&opts.fromMarkdownlint, "from-markdownlint", "", "Import settings from a markdownlint JSON config")
	cmd.Flags().StringVar(&opts.output, "output", ".mdmend.yml", "Output config file path")
	cmd.Flags().BoolVar(&opts.force, "force", false, "Overwrite existing config file")

	return cmd
}

func runInit(opts *initOptions) error {
	outputPath := opts.output
	if outputPath == "" {
		outputPath = ".mdmend.yml"
	}

	if !opts.force {
		if _, err := os.Stat(outputPath); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", outputPath)
		}
	}

	var cfg *config.Config
	var err error

	if opts.fromMarkdownlint != "" {
		cfg, err = loadMarkdownlintConfig(opts.fromMarkdownlint)
		if err != nil {
			return err
		}
	} else {
		cfg = config.Default()
	}

	data, err := config.ToYAML(cfg)
	if err != nil {
		return err
	}

	header := "# mdmend configuration\n# Generated by mdmend init\n\n"
	content := header + string(data)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil && filepath.Dir(outputPath) != "." {
		return err
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return err
	}

	fmt.Printf("Created %s\n", outputPath)
	return nil
}

func loadMarkdownlintConfig(path string) (*config.Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return config.ParseMarkdownlintJSON(data)
}
